image: node:18

include:
  - project: geoplateforme/templates
    ref: main
    file:
      - "/ci/docker.yml"

services:
  - redis:latest

cache:
  paths:
    - node_modules/

lint:
  script:
    - yarn --frozen-lockfile
    - yarn lint

test:
  script:
    - yarn --frozen-lockfile
    - yarn test
