services:
  api:
    build: .
    restart: always
    environment:
      REDIS_URL: redis://redis
    env_file:
      - .env
    ports:
      - '5000:5000'
    depends_on:
      - redis
    networks:
      - backend-network

  worker:
    build: .
    command: node worker.js
    restart: always
    environment:
      REDIS_URL: redis://redis
    depends_on:
      - redis
    networks:
      - backend-network

  redis:
    image: redis
    restart: always
    volumes:
      - redis-data:/data/db
    networks:
      - backend-network

volumes:
  redis-data: {}

networks:
  backend-network: {}
