version: '3.9'

services:
  api:
    build: .
    image: ${REGISTRY}gpf-geocodeur-api
    container_name: gpf-geocodeur-api
    environment:
      REDIS_URL: redis://redis-server
    env_file:
      - .env
    ports:
      - '5000:5000'
    depends_on:
      - redis-server
    links:
      - redis-server
    networks:
      - gpf-geocodeur-api-network
    volumes:
      - data-storage:/app/data

  worker:
    build: .
    image: ${REGISTRY}gpf-geocodeur-worker
    command: 'node worker.js'
    container_name: gpf-geocodeur-worker
    environment:
      REDIS_URL: redis://redis-server
    env_file:
      - .env
    depends_on:
      - redis-server
    networks:
      - gpf-geocodeur-api-network
    volumes:
      - data-storage:/app/data

  redis-server:
    image: redis
    restart: always
    container_name: redis-server
    ports:
      - '6379:6379'
    volumes:
      - redis-db:/data/db
    networks:
      - gpf-geocodeur-api-network

volumes:
  data-storage:
  redis-db:
    driver: local

networks:
  gpf-geocodeur-api-network:
