version: '3.9'

services:
  backend:
    build: .
    container_name: gpf-geocodeur-back
    environment:
      REDIS_URL: 'redis-server'
    env_file:
      - .env
    ports:
      - '5000:5000'
    depends_on:
      - redis-server
    links:
      - redis-server
    networks:
      - gpf-geocodeur-back

  redis-server:
    image: redis
    restart: always
    container_name: redis-server
    ports:
      - '6379:6379'
    volumes:
      - redis-db:/data/db
    networks:
      - gpf-geocodeur-back

volumes:
  redis-db:
    driver: local

networks:
  gpf-geocodeur-back:
    name: gpf-geocodeur-network
