version: '3.9'

services:
  api:
    build: .
    container_name: gpf-geocodeur-api
    environment:
      REDIS_URL: redis://redis-server
    env_file:
      - .env
    ports:
      - '5000:5000'
    depends_on:
      - redis-server
    links:
      - redis-server
    networks:
      - gpf-geocodeur-backend

  worker:
    build: .
    command: node worker.js
    container_name: gpf-geocodeur-worker
    environment:
      REDIS_URL: redis://redis-server
    depends_on:
      - redis-server
    networks:
      - gpf-geocodeur-backend

  redis-server:
    image: redis
    restart: always
    container_name: redis-server
    volumes:
      - redis-db:/data/db
    networks:
      - gpf-geocodeur-backend

volumes:
  redis-db:
    driver: local

networks:
  gpf-geocodeur-backend:
