version: '3.9'

services:
  api:
    build: .
    image: ${REGISTRY}gpf-geocodeur-api
    container_name: gpf-geocodeur-api
    environment:
      REDIS_URL: redis://redis-server
      ADDOK_SERVICE_URL: http://addok-server
      STORAGE_S3_REGION: ${STORAGE_S3_REGION}
      STORAGE_S3_ENDPOINT: ${STORAGE_S3_ENDPOINT}
      STORAGE_S3_ACCESS_KEY: ${STORAGE_S3_ACCESS_KEY}
      STORAGE_S3_SECRET_KEY: ${STORAGE_S3_SECRET_KEY}
      STORAGE_S3_BUCKET_NAME: ${STORAGE_S3_BUCKET_NAME}
    env_file:
      - .env
    ports:
      - '5000:5000'
    depends_on:
      - redis-server
    links:
      - redis-server
    networks:
      - gpf-geocodeur-api
    volumes:
      - data-storage:/app/data

  worker:
    build: .
    image: ${REGISTRY}gpf-geocodeur-worker
    command: 'node worker.js'
    container_name: gpf-geocodeur-worker
    environment:
      REDIS_URL: redis://redis-server
      ADDOK_SERVICE_URL: http://addok-server
    env_file:
      - .env
    depends_on:
      - redis-server
    networks:
      - gpf-geocodeur-api
    volumes:
      - data-storage:/app/data

  redis-server:
    image: redis
    restart: always
    container_name: redis-server
    ports:
      - '6379:6379'
    volumes:
      - redis-db:/data/db
    networks:
      - gpf-geocodeur-api

volumes:
  data-storage:
  redis-db:
    driver: local

networks:
  gpf-geocodeur-api:
    name: gpf-geocodeur-network
